# Placeholder chat to test a local LLM example. Will be revised. Generated by Claude Code.


from huggingface_hub import snapshot_download
from mlx_lm import load, generate

MODEL = "mlx-community/Ministral-3-3B-Instruct-2512-4bit"

print("Loading model...")
path = snapshot_download(MODEL, local_files_only=True)
model, tokenizer = load(path)
print("Ready! Type 'quit' to exit.\n")

history = []

while True:
    user_input = input("You: ").strip()
    if user_input.lower() in ("quit", "exit"):
        break
    if not user_input:
        continue

    history.append({"role": "user", "content": user_input})
    prompt = tokenizer.apply_chat_template(history, tokenize=False, add_generation_prompt=True)
    response = generate(model, tokenizer, prompt=prompt, max_tokens=512, verbose=False)

    print(f"Model: {response}\n")
    history.append({"role": "assistant", "content": response})